---
- name: Get Service Status
  hosts: all
  become: true

  tasks:
  - name: collect facts about system services
    service_facts:
    register: services_state

  - name: Debug
    debug:
      var: services_state
