---
- name: Searching for a file & registering results
  hosts: all
  become: true


  tasks:
  - name: Ansible register variable basic example
    shell: "find *.conf"
    args:
      chdir: "/etc"
    register: find_output

  - debug:
      var: find_output
